name = "targetbot"
main = "src/index.ts"
compatibility_date = "2025-11-01"
compatibility_flags = ["nodejs_compat"]
usage_model = "bundled"
workers_dev = true
node_compat = true

[kv_namespaces]
[[kv_namespaces]]
binding = "KV_USERS"
id = "kv_users_targetbot"

[[kv_namespaces]]
binding = "KV_LEADS"
id = "kv_leads_targetbot"

[[kv_namespaces]]
binding = "KV_META"
id = "kv_meta_targetbot"

[[kv_namespaces]]
binding = "KV_LOGS"
id = "kv_logs_targetbot"

[r2_buckets]
[[r2_buckets]]
binding = "R2_REPORTS"
bucket_name = "targetbot-reports"
