name = "th-reports"
main = "src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1

[triggers]
routes = ["https://th-reports.buyclientuz.workers.dev/*"]

[vars]
ENV = "production"

[observability.traces]
enabled = false
head_sampling_rate = 1

[[kv_namespaces]]
binding = "DB"
id = "0132cf582ce247d4b806a2be748e34c6"

[[r2_buckets]]
binding = "R2"
bucket_name = "botbucket"
preview_bucket_name = "botbucket"

[triggerstime]
crons = ["*/5 * * * *", "0 3 * * *"]
