name = "th-reports"
main = "src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = false
head_sampling_rate = 1

[[kv_namespaces]]
binding = "KV"
id = "0132cf582ce247d4b806a2be748e34c6"

[[kv_namespaces]]
binding = "LEADS_KV"
id = "00000000000000000000000000000000"

[[r2_buckets]]
binding = "R2"
bucket_name = "botbucket"
preview_bucket_name = "botbucket"

[vars]
FACEBOOK_API_VERSION = "v18.0"
FACEBOOK_TOKEN = ""

[triggers]
crons = ["*/5 * * * *", "0 3 * * *"]
