name = "th-reports"
main = "src/index.ts"
account_id = "02e61f874be22f0f3a6ee8f97ccccb1d"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = true

[[kv_namespaces]]
binding    = "REPORTS_NAMESPACE"
id         = "c55f82210ade457c93aff4fe2ba8b007"
preview_id = "c55f82210ade457c93aff4fe2ba8b007"

[[kv_namespaces]]
binding    = "BILLING_NAMESPACE"
id         = "c55f82210ade457c93aff4fe2ba8b007"
preview_id = "c55f82210ade457c93aff4fe2ba8b007"

[[kv_namespaces]]
binding    = "LOGS_NAMESPACE"
id         = "c55f82210ade457c93aff4fe2ba8b007"
preview_id = "c55f82210ade457c93aff4fe2ba8b007"

[env.production.vars]
ENVIRONMENT = "production"
