name = "th-reports"
main = "src/index.ts"
account_id = "02e61f874be22f0f3a6ee8f97ccccb1d"
compatibility_date = "2024-01-01"

# Add any bindings you need below (KV namespaces, R2 buckets, etc.).
# Example:
# [[kv_namespaces]]
# binding = "REPORTS_NAMESPACE"
# id = "<namespace-id>"
