name = "th-reports"
main = "src/index.js"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[vars]
DEFAULT_TZ = "Asia/Tashkent"

[[kv_namespaces]]
binding = "DB"
# Set the namespace ID in Cloudflare dashboard or via `wrangler kv namespace list`

[triggers]
crons = ["*/5 * * * *"]
