name = "th-reports"
main = "src/index.js"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = false
head_sampling_rate = 1

[[kv_namespaces]]
binding = "REPORTS_NAMESPACE"
id = "0132cf582ce247d4b806a2be748e34c6"

[[kv_namespaces]]
binding = "LOGS_NAMESPACE"
id = "0132cf582ce247d4b806a2be748e34c6"

[[kv_namespaces]]
binding = "BILLING_NAMESPACE"
id = "0132cf582ce247d4b806a2be748e34c6"

[[kv_namespaces]]
binding = "DB"
id = "0132cf582ce247d4b806a2be748e34c6"

[triggers]
crons = ["*/5 * * * *"]
