name = "th-reports"
main = "src/index.ts"
account_id = "02e61f874be22f0f3a6ee8f97ccccb1d"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "DB"
id = "<REPLACE_WITH_DB_NAMESPACE_ID>"

# Optional: add preview_id if you use separate namespaces for preview/dev environments.
# preview_id = "<REPLACE_WITH_DB_PREVIEW_NAMESPACE_ID>"
